<?php
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
    $icon = '<div><img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-banking-ticket.png" /></div>';
?>

<?= !$showInlineIcon ? null : $icon ?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?= $this->getMethodCode() ?>-instructions-content">

            <?= $showInlineIcon ? null : $icon?>

            <p class="ebanx-payment-method-desc">Pague com boleto bancário.</p>

            <?php include 'fields.phtml' ?>
        </div>
    </li>
    <li>
      <div class="total-to-pay">
        <p>Total a pagar com IOF (0.38%): <strong><?php echo $this->getLocalAmount('BRL') ?></strong>
      </div>
    </li>
</ul>
