<?php
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
$icon = '<img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-banking-ticket.png" />';

echo $showInlineIcon ? '<div class="ebanx-method-icon-box">' . $icon . '</div>' : null;
?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
  <li class="centinel-logos">
    <label class="ebanx-payment-method-desc">Pague com boleto bancário.</label>
    <?php if(!$showInlineIcon): ?>
      <div class="input-box">
        <?= $icon; ?>
      </div>
    <?php endif; ?>
  </li>
  <?php include 'fields.phtml' ?>
  <li>
    <?php include 'brazil/local_amount.phtml'; ?>
  </li>
</ul>
