<?php
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
    $icon = '<div><img src="' . $skin . 'frontend/base/default/ebanx/ebanx-banking-ticket.png" width="40" /></div>';
?>

<?= $showInlineIcon ? $icon : '' ?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?= $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?= $this->getMethodCode() ?>-instructions-content">

            <?= !$showInlineIcon ? $icon : '' ?>

            <p class="ebanx-payment-method-desc">Pague com boleto bancário.</p>

            <?php include 'fields.phtml' ?>
        </div>
    </li>
</ul>
