<?php
$skin           = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$_code          = $this->getMethodCode();
$skin           = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
$icon           = '<div><img src="' . $skin . 'frontend/base/default/ebanx/ebanx-credit-card-br.png" width="200" /></div>';
?>

<?= !$showInlineIcon ? null : $icon ?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?php echo $_code ?>" style="display:none;">

  <?= $showInlineIcon ? null : $icon ?>

  <p class="ebanx-payment-method-desc">Pagar com Cartão de Crédito.</p>

  <?php include 'fields.phtml' ?>

  <?php
  $savedCards = $this->getSavedCards();
  if (Mage::helper('ebanx')->saveCreditCardAllowed() && !empty($savedCards)): ?>
    <?php foreach ($savedCards as $card): ?>
      <li class="ebanx-credit-card-option">
        <input id="card[<?= $card->getEbanxCardId() ?>]" type="radio" name="selected_card" value="<?= $card->getEbanxCardId() ?>">
        <label for="card[<?= $card->getEbanxCardId() ?>]">
          <img src="<?= $skin ?>frontend/base/default/ebanx/icons/<?= $card->getBrand() ?>.png" width="30" />
          <span style="margin-left: 10px;">&bull;&bull;&bull;&bull; <?= substr($card->getMaskedNumber(), -4) ?></span>
        </label>
      </li>
    <?php endforeach; ?>
    <li class="ebanx-credit-card-option">
      <input id="card[newcard]" type="radio" name="selected_card" value="newcard">
      <label for="card[newcard]">Novo cartão</label>
      <?php include 'card/card-form.phtml' ?>
    </li>
  <?php else: ?>
  <?php include 'card/card-form.phtml' ?>
  <?php endif; ?>

  <li><p>Total a pagar com IOF (0.38%): <span id="cc-br-local-amount"><?php echo $this->getLocalAmount('BRL') ?></span>
    </p></li>
</ul>
