<?php
$skin           = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$_code          = $this->getMethodCode();
$skin           = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
$icon           = '<div><img src="' . $skin . 'frontend/base/default/ebanx/ebanx-credit-card-br.png" width="200" /></div>';
?>

<?= !$showInlineIcon ? null : $icon ?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?php echo $_code ?>" style="display:none;">

  <?= $showInlineIcon ? null : $icon ?>

  <p class="ebanx-payment-method-desc">Pagar com Cartão de Crédito.</p>

  <?php include 'fields.phtml' ?>

  <?php
  $savedCards = $this->getSavedCards();
  if (Mage::helper('ebanx')->saveCreditCardAllowed() && $savedCards->getSize()): ?>
    <?php foreach ($savedCards as $card): ?>
      <?php include 'card/saved-card.phtml' ?>
    <?php endforeach; ?>
    <li class="ebanx-credit-card-option">
      <input id="card[newcard]" type="radio" name="payment[selected_card]" value="newcard">
      <label for="card[newcard]">Novo cartão</label>
      <?php include 'card/card-form.phtml' ?>
    </li>

  <?php else: ?>
    <input id="card[newcard]" type="hidden" name="payment[selected_card]" value="newcard"/>
    <?php include 'card/card-form.phtml' ?>
  <?php endif; ?>

  <?php include 'card/instalments.phtml' ?>
  <li><p>Total a pagar com IOF (0.38%): <span id="cc-br-local-amount"><?php echo $this->getLocalAmount('BRL') ?></span>
    </p></li>
</ul>

<input type="hidden" name="payment[ebanx_mode]" id="<?php echo $_code ?>_mode"
       value="<?php echo Mage::helper('ebanx')->getMode() ?>"/>
<input type="hidden" name="payment[ebanx_integration_key]" id="<?php echo $_code ?>_integration_key"
       value="<?php echo Mage::helper('ebanx')->getPublicIntegrationKey() ?>"/>
<input type="hidden" name="payment[ebanx_country]" id="<?php echo $_code ?>_country" value="br"/>
<input type="hidden" name="payment[grand_total]" id="grand_total" value="<?php echo $this->getTotal() ?>"/>

<script>
  handleEbanxForm('br', 'cc');

  EBANXCreditCard.formatCardNumber(document.querySelector('input#ebanx_cc_br_cc_number'));
  EBANXCreditCard.formatCardCVC(document.querySelector('input#ebanx_cc_br_cc_cid'));
</script>

<style rel="stylesheet" type="text/css">
  .save-card,
  .new-card { display: none; }

  input[type=radio]:checked ~ .save-card { display: block; }
  input[type=radio]:checked ~ .new-card { display: block; }
</style>
