<?php
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $_code = $this->getMethodCode();
?>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <div>
        <img src="<?= $skin . 'frontend/base/default/ebanx/ebanx-credit-card-mx.png' ?>" width="115" />
    </div>

    <p class="ebanx-payment-method-desc">Pagar con Tarjeta de Crédito.</p>

    <?php include 'fields.phtml' ?>

    <li>
        <label for="<?php echo $_code ?>_cc_name" class="required"><em>*</em>Titular de la tarjeta</label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_name" name="payment[cc_name]"
                   title="<?php echo Mage::helper('core')->jsQuoteEscape('Titular de la tarjeta') ?>"
                   class="input-text required-entry validate-cc-name" value=""/>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em> Número de la tarjeta</label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]"
                   title="<?php echo Mage::helper('core')->jsQuoteEscape('Número de la tarjeta') ?>"
                   class="input-text required-entry validate-cc-number ebanx-format-cc-number" value=""/>
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em>Fecha de expiración</label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]"
                        class="month validate-cc-exp required-entry">
                    <?php
                    $_ccMonths = $this->getCcMonths();
                    $_ccMonths[0] = $this->__('Mes');
                    ?>
                    <?php foreach ($_ccMonths as $k => $v): ?>
                        <option value="<?php echo $k ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php
                $_ccExpYear = $this->getInfoData('cc_exp_year');

                $_ccYears = $this->getCcYears();
                $_ccYears[0] = $this->__('Año');
                ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($_ccYears as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em>Código de verificación</label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo Mage::helper('core')->jsQuoteEscape('Código de verificación') ?>"
                       class="input-text cvv required-entry ebanx-format-cvc-number validate-cc-cvn" id="<?php echo $_code ?>_cc_cid"
                       name="payment[cc_cid]" value=""/>
            </div>
        </div>
    </li>
    <?php $_instalmentOptions = $this->getInstalmentTerms() ?>
    <?php $_selected = $this->getInfoData('instalments') ?>
    <?php if (count($_instalmentOptions) > 1): ?>
        <li id="<?php echo $_code ?>-instalments-div">
            <label for="<?php echo $_code ?>_instalments" class="required"><em>*</em>Meses</label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_instalments" name="payment[instalments]" title="Meses"
                        class="required-entry validate-select">
                    <option value=""><?php echo $this->__('Selecione') ?></option>
                    <?php foreach ($_instalmentOptions as $_instalmentTerm): ?>
                        <option value="<?php echo $_instalmentTerm->instalmentNumber ?>">
                            <?php echo $this->formatInstalment($_instalmentTerm); ?>
                        </option>
                    <?php endforeach ?>
                </select>
                <input type="hidden" id="<?php echo $_code ?>_instalment_description"
                       name="payment[instalment_description]"
                       value="<?php echo $this->escapeHtml($this->getInfoData('instalment_description')) ?>"/>
            </div>
        </li>
    <?php endif ?>
    <input type="hidden" name="payment[ebanx_token]" id="ebanx_token"/>
    <input type="hidden" name="payment[ebanx_brand]" id="ebanx_brand"/>
    <input type="hidden" name="payment[ebanx_masked_card_number]" id="ebanx_masked_card_number"/>
    <input type="hidden" name="payment[ebanx_device_fingerprint]" id="ebanx_device_fingerprint"/>
    <input type="hidden" name="payment[ebanx_billing_instalments]" id="ebanx_billing_instalments"/>
    <input type="hidden" name="payment[ebanx_billing_cvv]" id="ebanx_billing_cvv"/>
    <input type="hidden" name="payment[ebanx_mode]" id="ebanx_mode"
           value="<?php echo Mage::helper('ebanx')->getMode() ?>"/>
    <input type="hidden" name="payment[ebanx_integration_key]" id="ebanx_integration_key"
           value="<?php echo Mage::helper('ebanx')->getPublicIntegrationKey() ?>"/>
    <input type="hidden" name="payment[ebanx_country]" id="ebanx_country" value="mx"/>
    <input type="hidden" name="payment[grand_total]" id="grand_total" value="<?php echo $this->getTotal() ?>"/>
</ul>

<script>
    handleEbanxForm('mx', 'cc');

    <?php if (count($_instalmentOptions) > 1): ?>
    if (typeof ebanxUpdateFireInterest !== 'undefined') {
        document.getElementById('<?php echo $_code ?>_instalments')
            .addEventListener('change', function () {
                ebanxUpdateFireInterest();
            });
    }
    <?php endif; ?>

    EBANXCreditCard.formatCardNumber(document.querySelector('input#ebanx_cc_mx_cc_number'));
    EBANXCreditCard.formatCardCVC(document.querySelector('input#ebanx_cc_mx_cc_cid'));
</script>
