<?php
    $_code = $this->getMethodCode();
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
    $icon = '<div><img src="' . $skin . 'frontend/base/default/ebanx/ebanx-credit-card-br.png" width="200" /></div>';
?>

<?php if($showInlineIcon) {
    echo $icon;
} ?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <?php if(!$showInlineIcon) {
        echo $icon;
    } ?>

    <p class="ebanx-payment-method-desc">Pagar com Cartão de Crédito.</p>

    <?php include 'fields.phtml' ?>

    <input type="hidden" name="payment[cc_name]" id="<?php echo $_code ?>_cc_name" value="Ebanx Magento Plugin"/>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em>Número do Cartão</label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number"
                   title="<?php echo Mage::helper('core')->jsQuoteEscape('Número do Cartão') ?>"
                   class="input-text required-entry validate-cc-number ebanx-format-cc-number" value=""/>
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em>Data de validade</label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]"
                        class="month required-entry validate-cc-exp">
                    <?php
                    $_ccMonths = $this->getCcMonths();
                    $_ccMonths[0] = $this->__('Mês');
                    ?>
                    <?php foreach ($_ccMonths as $k => $v): ?>
                        <option value="<?php echo $k ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php
                $_ccExpYear = $this->getInfoData('cc_exp_year');

                $_ccYears = $this->getCcYears();
                $_ccYears[0] = $this->__('Ano');
                ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($_ccYears as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em>Código de segurança</label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo Mage::helper('core')->jsQuoteEscape('Código de segurança') ?>"
                       class="input-text cvv required-entry validate-cc-cvn ebanx-format-cvc-number" id="<?php echo $_code ?>_cc_cid"
                       name="payment[cc_cid]" value=""/>
            </div>
        </div>
    </li>
    <?php $_instalmentOptions = $this->getInstalmentTerms() ?>
    <?php $_selected = $this->getInfoData('instalments') ?>
    <?php if (count($_instalmentOptions) > 1): ?>
        <li id="<?php echo $_code ?>-instalments-div">
            <label for="<?php echo $_code ?>_instalments" class="required"><em>*</em>Número de parcelas</label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_instalments" name="payment[instalments]" title="Instalments"
                        class="required-entry validate-select">
                    <option value="">Selecione</option>
                    <?php foreach ($_instalmentOptions as $_instalmentTerm): ?>
                        <option value="<?php echo $_instalmentTerm->instalmentNumber ?>">
                            <?php echo $this->formatInstalment($_instalmentTerm); ?>
                        </option>
                    <?php endforeach ?>
                </select>
                <input type="hidden" id="<?php echo $_code ?>_instalment_description"
                       name="payment[instalment_description]"
                       value="<?php echo $this->escapeHtml($this->getInfoData('instalment_description')) ?>"/>
            </div>
        </li>
    <?php endif ?>
    <input type="hidden" name="payment[ebanx_token]" id="<?php echo $_code ?>_token"/>
    <input type="hidden" name="payment[ebanx_brand]" id="<?php echo $_code ?>_brand"/>
    <input type="hidden" name="payment[ebanx_masked_card_number]" id="<?php echo $_code ?>_masked_card_number"/>
    <input type="hidden" name="payment[ebanx_device_fingerprint]" id="<?php echo $_code ?>_device_fingerprint"/>
    <input type="hidden" name="payment[ebanx_billing_instalments]" id="<?php echo $_code ?>_billing_instalments"/>
    <input type="hidden" name="payment[ebanx_billing_cvv]" id="<?php echo $_code ?>_billing_cvv"/>
    <input type="hidden" name="payment[ebanx_mode]" id="<?php echo $_code ?>_mode"
           value="<?php echo Mage::helper('ebanx')->getMode() ?>"/>
    <input type="hidden" name="payment[ebanx_integration_key]" id="<?php echo $_code ?>_integration_key"
           value="<?php echo Mage::helper('ebanx')->getPublicIntegrationKey() ?>"/>
    <input type="hidden" name="payment[ebanx_country]" id="<?php echo $_code ?>_country" value="br"/>
    <input type="hidden" name="payment[grand_total]" id="grand_total" value="<?php echo $this->getTotal() ?>"/>
</ul>

<script>
    handleEbanxForm('br', 'cc');

    <?php if (count($_instalmentOptions) > 1): ?>
        if (typeof ebanxUpdateFireInterest !== 'undefined') {
            document.getElementById('<?php echo $_code ?>_instalments')
            .addEventListener('change', function () {
                ebanxUpdateFireInterest();
            });
        }
    <?php endif; ?>

    EBANXCreditCard.formatCardNumber(document.querySelector('input#ebanx_cc_br_cc_number'));
    EBANXCreditCard.formatCardCVC(document.querySelector('input#ebanx_cc_br_cc_cid'));
</script>
