<?php
/**
 * @var Ebanx_Gateway_Helper_Data $helper
 */
$helper = Mage::helper('ebanx');
$ebanxCustomerDocument = '';
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$country = Mage::getSingleton('checkout/cart')->getQuote()->getShippingAddress()->getCountryId();

if ($helper->hasDocumentFieldAlreadyForMethod($this->getMethodCode())) return;

if (Mage::getSingleton('customer/session')->isLoggedIn()) {
  $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
  $customer = Mage::getModel('customer/customer')->load($customer_id);
  $ebanxCustomerDocument = $customer->getEbanxCustomerDocument();
}

?>
<li class="ebanx-compliance-fields">
  <label class="ebanx-document-label required" for="ebanx-document-<?= $this->getMethodCode() ?>">
    <em>*</em>
    <?= $helper->getLabelForComplianceField($this->getMethodCode()); ?>
  </label>
  <div class="input-box">
    <input
      type="text"
      id="ebanx-document-<?= $this->getMethodCode() ?>"
      name="ebanx-document[<?= $this->getMethodCode() ?>]"
      class="input-text required-entry"
      value="<?= $ebanxCustomerDocument ?>"
    />
  </div>

  <script type="text/javascript">
      inputHandler(document.querySelector('#ebanx-document-<?= $this->getMethodCode() ?>'), '<?= $country ?>');
  </script>
</li>
