<?php
/**
 * @var Ebanx_Gateway_Helper_Data $helper
 */
$helper = Mage::helper('ebanx');
$ebanxCustomerDocument = '';
$ebanxCustomerDocumentType = null;
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$country = Mage::getSingleton('checkout/cart')->getQuote()->getShippingAddress()->getCountryId();

if (Mage::getSingleton('customer/session')->isLoggedIn()) {
  $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
  $customer = Mage::getModel('customer/customer')->load($customer_id);
  $ebanxCustomerDocument = $customer->getEbanxCustomerDocument();
  $ebanxCustomerDocumentType = $customer->getEbanxCustomerDocumentType();
}

if ($helper->hasDocumentFieldAlreadyForMethod($this->getMethodCode()) && (!isset($customer) || $country !== 'AR' || $ebanxCustomerDocumentType)) {
  return;
}

?>
<li class="ebanx-compliance-fields">
  <?php if ($country === 'AR'): ?>
    <label for="ebanx-document-type-<?= $this->getMethodCode() ?>" class="ebanx-document-label required">
      Document Type
    </label>
    <div class="input-box">
      <select
        name="ebanx-document-type[<?= $country ?>]"
        id="ebanx-document-type-<?= $this->getMethodCode() ?>"
        title="Document Type"
        class="validate-select required-entry"
      >
        <option value="" selected>Select a document type</option>
        <option value="ARG_CUIT">CUIT</option>
        <option value="ARG_CUIL">CUIL</option>
        <option value="ARG_CDI">CDI</option>
      </select>
    </div>
  <?php endif ?>
  <label class="ebanx-document-label required" for="ebanx-document-<?= $this->getMethodCode() ?>">
    <em>*</em>
    <?= $helper->getLabelForComplianceField($this->getMethodCode()); ?>
  </label>
  <div class="input-box">
    <input
      type="text"
      id="ebanx-document-<?= $this->getMethodCode() ?>"
      name="ebanx-document[<?= $this->getMethodCode() ?>]"
      class="input-text required-entry"
      value="<?= $ebanxCustomerDocument ?>"
    />
  </div>

  <script type="text/javascript">
      inputHandler(document.querySelector('#ebanx-document-<?= $this->getMethodCode() ?>'), '<?= $country ?>');
      selectOption(document.querySelectorAll('#ebanx-document-type-<?= $this->getMethodCode() ?> > option'), '<?= $ebanxCustomerDocumentType ?>')
  </script>
</li>
