<?php $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>

<div>
    <img src="<?= $skin . 'frontend/base/default/ebanx/ebanx-pagoefectivo.png' ?>" width="40" />
</div>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">

            <p class="ebanx-payment-method-desc">Paga con PagoEfectivo.</p>

            <?php include 'fields.phtml' ?>
        </div>
    </li>
</ul>
