<?php
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
    $icon = '<div><img src="' . $skin . 'frontend/base/default/ebanx/ebanx-pagoefectivo.png" width="40" /></div>';
?>

<?= !$showInlineIcon ? null : $icon?>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">

        	<?= $showInlineIcon ? null : $icon?>

            <p class="ebanx-payment-method-desc">Paga con PagoEfectivo.</p>

            <?php include 'fields.phtml' ?>
        </div>
    </li>
    <li><p>Total a pagar en Sol peruano: <?php echo Mage::helper('ebanx/amount')->getLocalAmount('PEN') ?></p></li>
</ul>
