<?php $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>

<div>
    <img src="<?= $skin . 'frontend/base/default/ebanx/ebanx-eft.png' ?>" width="40" />
</div>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <p class="ebanx-payment-method-desc">Paga con PSE – Pago Seguros en Línea.</p>

            <?php include 'fields.phtml' ?>

            <p>
                <select name="ebanx_pse_bank" id="ebanx_pse_bank">
                    <?php foreach ($this->getBanksList() as $key => $value): ?>
                        <option value="<?php echo $key ?>"><?php echo $value ?></option>
                    <?php endforeach ?>
                </select>
            </p>
        </div>
    </li>
</ul>
