<?php $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>

<div>
    <img src="<?= $skin . 'frontend/base/default/ebanx/ebanx-safetypay.png' ?>" width="40" />
</div>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <p class="ebanx-payment-method-desc">Paga con SafetyPay.</p>

            <?php include 'fields.phtml' ?>

            <p>
                <label for="ebanx_safetypay_type_cash">
                    <input type="radio" id="ebanx_safetypay_type_cash" name="ebanx_safetypay_type" value="Cash" checked>
                    Cash
                </label>
            </p>
            <p>
                <label for="ebanx_safetypay_type_online">
                    <input type="radio" id="ebanx_safetypay_type_online" name="ebanx_safetypay_type" value="Online">
                    Online
                </label>
            </p>
        </div>
    </li>
</ul>
