<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php include 'fields.phtml' ?>

            <p>Paga con SafetyPay.</p>

            <p>
                <label for="ebanx_safetypay_type_cash">
                    <input type="radio" id="ebanx_safetypay_type_cash" name="ebanx_safetypay_type" value="Cash" checked>
                    Cash
                </label>
            </p>
            <p>
                <label for="ebanx_safetypay_type_online">
                    <input type="radio" id="ebanx_safetypay_type_online" name="ebanx_safetypay_type" value="Online">
                    Online
                </label>
            </p>
        </div>
    </li>
</ul>
