<?php
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
$icon = '<img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-sencillito.png" />';
$warningTexts = Mage::helper('ebanx')->getSandboxWarningText();
$isSandbox = Mage::helper('ebanx')->isSandboxMode();
$sandboxTag = $isSandbox ? '<div class="sandbox-form-tag">' . $warningTexts['tag'] . '</div>' : '';

echo $showInlineIcon ? '<div class="ebanx-method-icon-box">' . $icon . $sandboxTag . '</div>' : null;
?>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <?php include 'sandbox-warning.phtml' ?>
  <li class="centinel-logos">
    <label class="ebanx-payment-method-desc">Paga con Sencillito.</label>
    <?php if(!$showInlineIcon): ?>
      <div class="input-box">
        <?= $icon; ?>
      </div>
    <?php endif; ?>
  </li>
  <?php include 'fields.phtml' ?><li>
  <li>
    <div class="total-to-pay">
      <p>Total a pagar en Peso chileno: <strong><?php echo $this->getLocalAmount('CLP') ?></strong></p>
    </div>
  </li>
</ul>
