<?php
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
    $icon = '<div><img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-tef.png" /></div>';
?>

<?= !$showInlineIcon ? null : $icon?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">

            <?= $showInlineIcon ? null : $icon?>

            <p class="ebanx-payment-method-desc">Selecione o seu banco. A seguir, você será redirecionado para concluir o pagamento pelo seu internet
                banking.</p>

            <?php include 'fields.phtml' ?>

            <p>
                <label for="ebanx_tef_itau">
                    <input type="radio" id="ebanx_tef_itau" name="ebanx_tef" value="itau" checked>
                    Itaú
                </label>
            </p>
            <p>
                <label for="ebanx_tef_bradesco">
                    <input type="radio" id="ebanx_tef_bradesco" name="ebanx_tef" value="bradesco">
                    Bradesco
                </label>
            </p>
            <p>
                <label for="ebanx_tef_bb">
                    <input type="radio" id="ebanx_tef_bb" name="ebanx_tef" value="bancodobrasil">
                    Banco do Brasil
                </label>
            </p>
            <p>
                <label for="ebanx_tef_banrisul">
                    <input type="radio" id="ebanx_tef_banrisul" name="ebanx_tef" value="banrisul">
                    Banrisul
                </label>
            </p>
        </div>
    </li>
    <li>
      <div class="total-to-pay">
        <p>Total a pagar com IOF (0.38%): <strong><?php echo $this->getLocalAmount('BRL') ?></strong>
      </div>
    </li>
</ul>
