<?php
    $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
    $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
    $icon = '<div><img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-account.png" /></div>';
?>

<?= !$showInlineIcon ? null : $icon?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">

        	<?= $showInlineIcon ? null : $icon?>

            <p class="ebanx-payment-method-desc">Pague usando o saldo da sua conta do EBANX.</p>

            <?php include 'fields.phtml' ?>
        </div>
    </li>
    <li>
      <div class="total-to-pay">
        <p>Total a pagar com IOF (0.38%): <strong><?php echo $this->getLocalAmount('BRL') ?></strong>
        <input type="hidden" name="payment[grand_total]" id="grand_total_<?php echo $this->getMethodCode() ?>" value="<?php echo $this->getTotal() ?>"/>
      </div>
    </li>
</ul>
