<?php $skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>

<ul class="form-list ebanx-payment-method ebanx-br-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <div>
                <img src="<?= $skin . 'frontend/base/default/ebanx/ebanx-account.png' ?>" width="70" />
            </div>

            <p class="ebanx-payment-method-desc">Pague usando o saldo da sua conta do EBANX.</p>

            <?php include 'fields.phtml' ?>
        </div>
    </li>
</ul>
