<?php
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
$showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
$icon = '<img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-webpay.png" />';

$showInlineIcon ? '<div class="ebanx-method-icon-box">' . $icon . '</div>' : null;
?>

<ul class="form-list ebanx-payment-method ebanx-es-method" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <li class="centinel-logos">
    <label class="ebanx-payment-method-desc">Paga con Webpay.</label>
    <?php if(!$showInlineIcon): ?>
      <div class="input-box">
        <?= $icon; ?>
      </div>
    <?php endif; ?>
  </li>
  <?php include 'fields.phtml' ?><li>
  <li><p>Total a pagar en Peso chileno: <?php echo $this->getLocalAmount('CLP') ?></p></li>
</ul>
