dist: trusty
sudo: required

language: php

services:
  - docker

php:
  - 5.4

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache

install: composer update

before_script:
  - sudo service mysql stop
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

env:
  matrix:
    - TEST_COUNTRY=argentina
    - TEST_COUNTRY=brazil
    - TEST_COUNTRY=chile
    - TEST_COUNTRY=colombia
    - TEST_COUNTRY=ecuador
    - TEST_COUNTRY=mexico
    - TEST_COUNTRY=peru

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      env: TEST_COUNTRY=
      script: bash ./tests/bin/lint.sh
    - stage: release
      script:
        - cd $TRAVIS_BUILD_DIR
        - php deploy
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: releases
          api_key:
            secure: QB9VKYBWfH7AxUg6OQ1hp8WEiIV9A8An/DpWWmjidhsCpkfeoxgqF+Dq6ugl6aYKPbv2loWnDnq8ry7S9Eja3ecqKkRSC/XHtzwI+K3QRklaG4AUb7Pu5hd4XhYLpwJiOrPl4eMyRmNdVse4HeE/rlQF/YOHMz2t3CgUBkJsKyD6W47UOzbRmqZthf6FU7zJNrvdYEXHxe10czpCeRBJFI4g7DHqiEdBgXja3Ypcxfoh6678x2PXJfyc/5/UVm564F1WHdO8prZ/OxePzV14H1SdmTQMUFQ+3nOsdhlSvEMr+YrkGOjMV3odrN9DfiZzZt+iNvIVfxrBzDB82aFcIHOY4y/0E6r+ImsaNrFPPpd0e5tigbFWC0IAQlFdpxM5OKatxLI4jNq583e2tBBTJXyeERsykLtmGb6RKYW5X+FBgNI8WNNnkxbgZHMdScmhzXTFbPAkGBx13zu4ZNtzA4EkpzeZr6Jd9Ec7i44CNer7f4P6HmBd0bXZ7f1fsLGgwj01upWBU19ohE2hKpNukiXfcZA1wEagKofnEcFoz6pKpC5KTrBL75EUdeSD/iNEpsgnvTkXb0mJdOeNu0GVzPhBzpW7EC+udr6CbRwad/zHaB/3zWN8hM18oXoIQwAPdTiXUREn4HI/3Hu3nJFAKVRnPNZSnInrxNten4cyP8o=
          file: ebanx_gateway-${TRAVIS_TAG}.tgz
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
script:
  - bash ./tests/bin/test.sh

