dist: trusty
sudo: required

language: php

services:
  - docker

php:
  - 5.5

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache

install: composer update

before_script:
  - sudo service mysql stop
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

env:
  matrix:
    - TEST_COUNTRY=argentina
    - TEST_COUNTRY=brazil
    - TEST_COUNTRY=chile
    - TEST_COUNTRY=colombia
    - TEST_COUNTRY=ecuador
    - TEST_COUNTRY=mexico
    - TEST_COUNTRY=peru

stages:
  - Lint
  - Tests

jobs:
  include:
    - stage: Lint
      env: TEST_COUNTRY=
      script: bash ./tests/bin/lint.sh

script:
  - bash ./tests/bin/test.sh
