dist: trusty
sudo: required

language: php

services:
  - docker

php:
  - 5.4

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/tests/node_modules
    - $HOME/.composer/cache
    - ~/.npm
    - ~/.cache

env:
  matrix:
  - TEST_COUNTRY=argentina
  - TEST_COUNTRY=brazil
  - TEST_COUNTRY=chile
  - TEST_COUNTRY=colombia
  - TEST_COUNTRY=ecuador
  - TEST_COUNTRY=mexico
  - TEST_COUNTRY=peru

before_install:
  - nvm install stable
  - nvm use stable

install: composer update

before_script:
  - sudo service mysql stop
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      env: TEST_COUNTRY=
      script: bash ./tests/bin/lint.sh
    - stage: release
      script:
        - cd $TRAVIS_BUILD_DIR
        - php deploy
      env:
        - TEST_COUNTRY=
      deploy:
        - provider: releases
          api_key:
            secure: mNDqbbkPBsYcRE+zQ3hZ74QjGyLTM6IWYcmD/qLy3Sxf662ANwIltTveA/ME9yjhASiyLyt68B+GJrO3ATO829yZpicoGypNkoHCDGcd9WH7km8faqabhsUZSF1aY2/GY5HLJ/w7i83GrWqkJB6K8qt7pyqEgikjOe6hZYh7LkvES4OwPirEtNpUj+dUC2Qy7VemCoSdPSI/z8U5hNaGnECCS/Qk+xpOS2QcwLsCf4hY/snUVhHXYi3u/blXkiIfOZeVJn2oE+WeLjhuu10hKu4t6Gx2KMW8SMYxhb8z9ml1cragOn5sE8dFvqNAvXRd9UbupoKMqQZbZiaH5n5YoTxLVlhzUhF7KvYM+IGLAsZPwsaNgOq//0gCM2pA554CAsmim7r+MDAzHzZHEGIKyFIrJSnPYu2wev0iPQ/2rKFc8B/gFsofwpX8qrJU35mJGBLsuvKJ0oHvQML+9n1unBtMHrmtq9PULh6NYlQhHrl6I3ORh3kJ8w+gV49BuK3w+AbWfasZpaZpmzm6M7glgUKcONMWlcdJkHP7EGP3BTbTOkA2NBlH3a+otclHL+I7tvc+FsW5cSibV1JCwUBlo1L7tRirXwYEIxeGvclWdVGPV7BkQI4m/cTo/BoWj+39bVMcCApdClEvDYQm5DZeHZoLJh9RcIKW/AO11zSzdR4=
          file: ebanx_gateway-${TRAVIS_TAG}.tgz
          skip_cleanup: true
          on:
            tags: true
            all_branches: true
script:
  - bash ./tests/bin/test.sh

