version: '3'

services:
  magento:
    image: alexcheng/magento:latest
    container_name: magento
    ports:
      - ${MAGENTO_EXTERNAL_PORT:-80}:80
    links:
      - magento_db
    volumes:
      - ./app/code/community/Ebanx/:/var/www/html/app/code/community/Ebanx/
      - ./app/etc/modules/Ebanx_Gateway.xml:/var/www/html/app/etc/modules/Ebanx_Gateway.xml
      - ./app/design/adminhtml/default/default/layout/ebanx.xml:/var/www/html/app/design/adminhtml/default/default/layout/ebanx.xml
      - ./app/design/adminhtml/default/default/template/ebanx/:/var/www/html/app/design/adminhtml/default/default/template/ebanx/
      - ./app/design/frontend/base/default/layout/ebanx.xml:/var/www/html/app/design/frontend/base/default/layout/ebanx.xml
      - ./app/design/frontend/base/default/template/ebanx/:/var/www/html/app/design/frontend/base/default/template/ebanx/
      - ./skin/adminhtml/default/default/ebanx/:/var/www/html/skin/adminhtml/default/default/ebanx/
      - ./skin/frontend/base/default/ebanx/:/var/www/html/skin/frontend/base/default/ebanx/
      - ./lib/Ebanx/:/var/www/html/lib/Ebanx/
      - ./js/ebanx/:/var/www/html/js/ebanx/
      - ./.dev/index.php:/var/www/html/index.php
      - /var/www/html
    environment:
      MYSQL_HOST: magento_db
      MYSQL_DATABASE: ${MAGENTO_DATABASE}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MAGENTO_LOCALE: en_US
      MAGENTO_TIMEZONE: America/Sao_Paulo
      MAGENTO_DEFAULT_CURRENCY: USD
      MAGENTO_ADMIN_USERNAME: ${ADMIN_USER}
      MAGENTO_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MAGENTO_ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME}
      MAGENTO_ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      MAGENTO_ADMIN_EMAIL: ${ADMIN_EMAIL}
      MAGENTO_URL: http://localhost:${MAGENTO_EXTERNAL_PORT:-80}
      EBANX_TEST_MODE: 1

  magento_db:
    image: mysql:5
    container_name: magento_db
    ports:
      - ${MYSQL_EXTERNAL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    volumes:
      - ./.data:/var/lib/mysql
