<?php
$documentFields = array(
  Mage::getStoreConfig('payment/ebanx_settings/cpf_field'),
  Mage::getStoreConfig('payment/ebanx_settings/cnpj_field'),
  Mage::getStoreConfig('payment/ebanx_settings/rut_field'),
  Mage::getStoreConfig('payment/ebanx_settings/dni_field')
);
$taxvatDocumentFields = array_filter($documentFields, function($field) {
  return $field === 'taxvat';
});

$taxvatShow = Mage::getStoreConfig('customer/address/taxvat_show');

if (!empty($taxvatDocumentFields) && ($taxvatShow === 'opt' || $taxvatShow === 1)):
?>
<script type="text/javascript">
//<![CDATA[
  window.onload = function () {
    hideTaxVat();
  };
//]]>
</script>
<?php
endif;
