<?php
$documentFields = array(
  Mage::getStoreConfig('payment/ebanx_settings/cpf_field'),
  Mage::getStoreConfig('payment/ebanx_settings/cnpj_field'),
  Mage::getStoreConfig('payment/ebanx_settings/rut_field'),
  Mage::getStoreConfig('payment/ebanx_settings/dni_field')
);
$taxvatDocumentFields = array_filter($documentFields, function($field) {
  return $field === 'taxvat';
});

$session = Mage::getSingleton('customer/session');

if (!empty($taxvatDocumentFields) && $session->isLoggedIn() && $session->getCustomer()->getDefaultBillingAddress()):
  $countryCode = $session->getCustomer()->getDefaultBillingAddress()->getCountry();

  if ($countryCode) {
    $label = Mage::helper('ebanx')->getLabelForComplianceFieldByCountry($countryCode);
  }
  ?>
  <script type="text/javascript">
  //<![CDATA[
    window.onload = function () {
      initTaxVatLabel('<?= $label;?>');
      inputHandler(document.querySelector('#taxvat'), '<?= $countryCode ?>');
    };
  //]]>
  </script>
  <?php
endif;
