<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <p>Pagar con Tarjeta de Debito.</p>
    </li>
    <?php include 'fields.phtml' ?>
    <li>
        <label for="<?php echo $_code ?>_dc_name" class="required"><em>*</em><?php echo $this->__('Nome no Cartão') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_dc_name" name="payment[dc_name]" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Nome no Cartão')) ?>" class="input-text validate-dc-name" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_dc_number" class="required"><em>*</em><?php echo $this->__('Número do Cartão') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_dc_number" name="payment[dc_number]" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Número do Cartão')) ?>" class="input-text validate-dc-number" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_dc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Data de validade') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[dc_exp_month]" class="month validate-dc-exp required-entry">
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_dcExpYear = $this->getInfoData('dc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[dc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <li id="<?php echo $_code ?>_dc_type_cvv_div">
        <label for="<?php echo $_code ?>_dc_cid" class="required"><em>*</em><?php echo $this->__('Código de segurança') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Código de segurança')) ?>" class="input-text cvv required-entry validate-dc-cvn" id="<?php echo $_code ?>_dc_cid" name="payment[dc_cid]" value="" />
            </div>
        </div>
    </li>
    <?php $_instalmentOptions = $this->getInstalmentTerms() ?>
    <?php $_selected = $this->getInfoData('instalments') ?>
    <?php if (count($_instalmentOptions) > 1): ?>
    <li id="<?php echo $_code ?>-instalments-div">
        <label for="<?php echo $_code ?>_instalments" class="required"><em>*</em><?php echo $this->__('Instalments') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_instalments" name="payment[instalments]" title="<?php echo $this->__('Instalments') ?>" class="required-entry validate-select">
                <option value=""><?php echo $this->__('Selecione') ?></option>
                <?php foreach ($_instalmentOptions as $_instalmentTerm): ?>
                    <option value="<?php echo $_instalmentTerm->instalmentNumber ?>">
                        <?php echo $this->formatInstalment($_instalmentTerm); ?>
                    </option>
                <?php endforeach ?>
            </select>
            <input type="hidden" id="<?php echo $_code ?>_instalment_description" name="payment[instalment_description]" value="<?php echo $this->escapeHtml($this->getInfoData('instalment_description')) ?>" />
        </div>
    </li>
    <?php endif ?>
    <input type="hidden" name="payment[ebanx_token]" id="ebanx_token" />
    <input type="hidden" name="payment[ebanx_brand]" id="ebanx_brand" />
    <input type="hidden" name="payment[ebanx_masked_card_number]" id="ebanx_masked_card_number" />
    <input type="hidden" name="payment[ebanx_device_fingerprint]" id="ebanx_device_fingerprint" />
    <input type="hidden" name="payment[ebanx_billing_instalments]" id="ebanx_billing_instalments" />
    <input type="hidden" name="payment[ebanx_billing_cvv]" id="ebanx_billing_cvv" />
    <input type="hidden" name="payment[ebanx_mode]" id="ebanx_mode" value="<?php echo Mage::helper('ebanx')->getMode() ?>" />
    <input type="hidden" name="payment[ebanx_integration_key]" id="ebanx_integration_key" value="<?php echo Mage::helper('ebanx')->getPublicIntegrationKey() ?>" />
    <input type="hidden" name="payment[ebanx_country]" id="ebanx_country" value="mx" />
</ul>

<script type="text/javascript">
    //<![CDATA[
    handleEbanxForm('mx', 'dc');
    //]]>
</script>
