<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php include 'fields.phtml' ?>

            <p>Paga con PSE – Pago Seguros en Línea.</p>

            <p>
                <select name="ebanx_pse_bank" id="ebanx_pse_bank">
                    <?php foreach ($this->getBanksList() as $key => $value): ?>
                        <option value="<?php echo $key ?>"><?php echo $value ?></option>
                    <?php endforeach ?>
                </select>
            </p>
        </div>
    </li>
</ul>
