<div class="banking-ticket__desc">
    <br/>
    <p class="magento-thankyou-order-received"><?php echo $this->__("Pronto, seu boleto foi gerado, %s.", $this->getOrder()->getBillingAddress()->getFirstname()) ?></p>
    <p><?php echo $this->__("Mandamos uma cópia para o email %s.", "<strong>" . $this->getOrder()->getCustomerEmail() . "</strong>") ?></p>
    <p>
        <?php echo $this->__("- Não se esqueça, ele vence %s. Depois disso não é mais possível realizar o pagamento.", "<strong>" . $this->getEbanxDueDate() . "</strong>") ?></p>
        <?php echo $this->__("- Dica: Além dos bancos e casas lotéricas você também pode pagar pelo seu internet banking, sem sair de casa."); ?>
    </p>
    <p><?php echo $this->__('Ficou alguma dúvida? A gente te <a href="%s" target="_blank">ajuda</a>', "https://www.ebanx.com/br/ajuda/pagamentos/boleto-bancario") ?>.</p>
</div>

<hr>

<div class="banking-ticket__barcode">
    <div class="banking-ticket__barcode-code">
        <?php
        $barCodeFormated = $this->getEbanxBarCodeFormated();
        echo $barCodeFormated['boleto1'] . '.' . $barCodeFormated['boleto2'] . ' ' . $barCodeFormated['boleto3'] . '.' . $barCodeFormated['boleto4'] . ' ' . $barCodeFormated['boleto5'] . '.' . $barCodeFormated['boleto6'] . ' ' . $barCodeFormated['boleto7'] . ' ' . $barCodeFormated['boleto8'];
        ?>
    </div>
    <div class="banking-ticket__barcode-copy">
        <button type="button" class="button ebanx-button--copy" data-clipboard-text="<?php echo $this->getEbanxBarCode(); ?>"><?php echo $this->__('Copiar'); ?></button>
    </div>
</div>

<hr>

<div class="banking-ticket__actions">
    <div class="ebanx-button--group ebanx-button--group-two">
        <a href="<?php echo $this->getEbanxUrlPdf(); ?>" target="_blank" class="button banking-ticket__action"><?php echo $this->__('Salvar em PDF'); ?></a>
        <a href="<?php echo $this->getEbanxUrlPrint() ?>" target="_blank" class="button banking-ticket__action"><?php echo $this->__('Imprimir boleto'); ?></a>
    </div>
</div>
<?php

echo $this->getEbanxPaymentHash();