<?php
  $customer = $this->getCustomer();
  $order = $this->getOrder();
  $payment = $this->getPayment();
  $core = Mage::helper('core');
?>

<div class="ebanx-details">
  <p>Seu pagamento foi confirmado, <?= $customer['firstname'] ?>.</p>
  <p>Valor a pagar com IOF (0.38%): <?= $core->formatPrice($order->getGrandTotal() * 1.0038) ?></p>
  <!-- <p>4 parcelas de € 120,46</p> -->
  <p>Pago com Cartão <?= ucfirst($payment->getCcType()) ?>: <?= $payment->getCcLast4() ?></p>
  <p>Obrigado por ter comprado conosco.</p>
</div>
