<?php $_instalmentOptions = $this->getInstalmentTerms() ?>
<?php $_selected = $this->getInfoData('instalments') ?>
<?php if (count($_instalmentOptions) > 1): ?>
  <li id="<?php echo $_code ?>-instalments-div">
    <label for="<?php echo $_code ?>_instalments" class="required"><em>*</em><?= $text['instalments'] ?></label>
    <div class="input-box">
      <select id="<?php echo $_code ?>_instalments" name="payment[instalments]" title="Instalments"
              class="required-entry validate-select">
        <?php foreach ($_instalmentOptions as $_instalmentTerm): ?>
          <option
            value="<?php echo $_instalmentTerm->instalmentNumber ?>"
            data-local-amount="<?php echo Mage::app()->getLocale()->currency($localCurrency)->toCurrency($_instalmentTerm->localAmountWithTax * $_instalmentTerm->instalmentNumber) ?>"
          >
            <?php echo $this->formatInstalment($_instalmentTerm, $localCurrency); ?>
          </option>
        <?php endforeach ?>
      </select>
      <input type="hidden" id="<?php echo $_code ?>_instalment_description"
             name="payment[instalment_description]"
             value="<?php echo $this->escapeHtml($this->getInfoData('instalment_description')) ?>"/>

      <script>
        if (typeof ebanxUpdateFireInterest !== 'undefined') {
          document.getElementById('<?php echo $_code ?>_instalments')
            .addEventListener('change', function () {
              ebanxUpdateFireInterest();
            });
        }

        var selectInstalment = document.getElementById('<?= $_code ?>_instalments');

        var updateInstalment = function (){
          var text = document.getElementById('cc-<?= $lowerCountry ?>-local-amount');
          text.innerHTML = '<strong>' + selectInstalment.options[selectInstalment.selectedIndex].getAttribute('data-local-amount') + '</strong>';
        };

        if (selectInstalment) {
          updateInstalment();
          selectInstalment.addEventListener('change', updateInstalment);
        }
      </script>
    </div>
  </li>
<?php endif ?>
