<?php
  $text           = $this->getText();
  $lowerCountry   = $this->country;
  $localCurrency  = $this->localCurrency;
  $skin           = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
  $_code          = $this->getMethodCode();
  $showInlineIcon = Mage::helper('ebanx')->hasToShowInlineIcon();
  $icon           = '<img class="ebanx-method-icon" src="' . $skin . 'frontend/base/default/ebanx/ebanx-credit-card-' . $lowerCountry . '.png" />';
  $showIof = Mage::getStoreConfig('payment/ebanx_settings/iof_local_amount');
  $warningTexts = Mage::helper('ebanx')->getSandboxWarningText();
  $isSandbox = Mage::helper('ebanx')->isSandboxMode();
  $sandboxTag = $isSandbox ? '<div class="sandbox-form-tag">' . $warningTexts['tag'] . '</div>' : '';

echo $showInlineIcon ? '<div class="ebanx-method-icon-box">' . $icon . $sandboxTag . '</div>' : null;
?>

<ul class="form-list ebanx-payment-method ebanx-<?= $lowerCountry ?>-method" id="payment_form_<?php echo $_code ?>" style="display:none;">
  <?php include __DIR__ . '/../sandbox-warning.phtml'; ?>
  <li class="centinel-logos">
    <label class="ebanx-payment-method-desc"><?= $text['method-desc'] ?></label>
      <?php if(!$showInlineIcon): ?>
        <div class="input-box">
          <?= $icon; ?>
        </div>
      <?php endif; ?>
  </li>

  <?php
    include __DIR__ . '/../fields.phtml';
    $savedCards = $this->getSavedCards();
    if (Mage::helper('ebanx')->saveCreditCardAllowed() && $savedCards && $savedCards->getSize()):
  ?>

  <?php foreach ($savedCards as $card): ?>
    <?php include 'saved-card.phtml' ?>
  <?php endforeach; ?>

  <li class="ebanx-credit-card-option">
    <input id="card[newcard]" type="radio" name="payment[selected_card]" value="newcard">
    <label for="card[newcard]"><?= $text['newcard'] ?></label>
    <div class="new-card">
      <?php include 'card-form.phtml' ?>
    </div>
  </li>

  <?php else: ?>
    <li>
      <input id="card[newcard]" type="hidden" name="payment[selected_card]" value="newcard"/>
      <div class="container-new-card">
        <?php include 'card-form.phtml' ?>
      </div>
    </li>
  <?php endif; ?>

  <?php include 'instalments.phtml' ?>

  <li>
    <div class="total-to-pay">
      <p>
        <?= $text['local-amount'] ?><span id="cc-<?= $lowerCountry ?>-local-amount"><strong><?php echo $showIof ? $this->getLocalAmount($localCurrency) : $this->getLocalAmountWithoutTax('BRL') ?></strong></span>
      </p>
    </div>
    <input type="hidden" name="payment[ebanx_mode]" id="<?php echo $_code ?>_mode"
           value="<?php echo Mage::helper('ebanx')->getMode() ?>"/>
    <input type="hidden" name="payment[ebanx_integration_key]" id="<?php echo $_code ?>_integration_key"
           value="<?php echo Mage::helper('ebanx')->getPublicIntegrationKey() ?>"/>
    <input type="hidden" name="payment[ebanx_country]" id="<?php echo $_code ?>_country" value="<?= $lowerCountry ?>"/>
    <input type="hidden" name="payment[grand_total]" id="grand_total" value="<?php echo $this->getTotal() ?>"/>
  </li>
</ul>


<script type="text/javascript">
  handleEbanxForm('<?= $lowerCountry ?>', 'cc', 'payment_form_<?= $_code ?>');
  EBANXCreditCard.formatCardNumber(document.querySelector('input#<?= $_code ?>_cc_number'));
  EBANXCreditCard.formatCardCVC(document.querySelector('input#<?= $_code ?>_cc_cid'));
</script>
