<?php
  $brazilAllowedDocumentFields = explode(',', Mage::getStoreConfig('payment/ebanx_settings/brazil_taxes'));
  $maskTaxvat = Mage::getStoreConfig('payment/ebanx_settings/mask_taxvat_field');
?>

<!-- EBANX Custom Variables -->
<script type="text/javascript">
//<![CDATA[
  var EBANXData = {
    brazilAllowedDocumentFields: <?= json_encode($brazilAllowedDocumentFields) ?>,
    maskTaxVat: <?= $maskTaxvat ? 'true' : 'false' ?>
  };
//]]>
</script>
