<?php
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>
<div class="page-title">
  <h1><?= $this->__('Payment cards') ?></h1>
</div>

<?= $this->getMessagesBlock()->getGroupedHtml() ?>
<?= $this->getChildHtml('pager'); ?>

<?php if ($this->getCards()->getSize()): ?>
  <form  id="credit-card-list-form" method="post" action="<?= $this->escapeUrl($this->getFormUrl()) ?>">

    <table class="data-table" id="my-credit-cards-table">
      <col width="1" />
      <col />
      <col width="1" />
      <thead>
      <tr>
        <th></th>
        <th><?= $this->__('Card') ?></th>
      </tr>
      </thead>
      <tbody>
      <?php foreach ($this->getCards() as $card): ?>
        <tr>
          <td>
            <input type="checkbox" class="checkbox related-checkbox" value="<?= $card->getEbanxCardId(); ?>" id="card[<?= $card->getEbanxCardId(); ?>]" name="card[]" />
          </td>
          <td>
            <label for="card[<?= $card->getEbanxCardId(); ?>]">
              <img style="float: left;" src="<?= $skin ?>frontend/base/default/ebanx/icons/<?= $card->getBrand() ?>.png" width="30"/>
              <span style="float: left; margin-left: 10px;">&bull;&bull;&bull;&bull; <?= substr($card->getMaskedNumber(), -4) ?></span>
            </label>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>

    <script type="text/javascript">
      decorateTable('my-credit-cards-table');
    </script>

    <?= $this->getChildHtml('pager') ?>

    <div class="buttons-set">
      <p class="back-link">
        <a href="<?= $this->escapeUrl($this->getBackUrl()) ?>">
          <small>&laquo;&nbsp;</small><?= $this->__('Back') ?>
        </a>
      </p>
      <button class="button" type="submit" title="<?= $this->__('Remove') ?>">
        <span><span><?= $this->__('Remove') ?></span></span>
      </button>
    </div>
  </form>
<?php else: ?>

  <p><?= $this->__('You have no saved credit cards yet.') ?></p>
  <div class="buttons-set">
    <p class="back-link">
      <a href="<?= $this->escapeUrl($this->getBackUrl()) ?>">
        <small>&laquo;&nbsp;</small><?= $this->__('Back') ?>
      </a>
    </p>
  </div>

<?php endif; ?>
