<?php
$skin = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>

<div class="ebanx-details">
    <p class="text-center">Baixe o app para IOS ou Android da Conta EBANX.</p>
    <input type="hidden" data-doraemon-hash="<?= $this->getPayment()->getEbanxPaymentHash() ?>" />

    <div class="ebanx-groups ebanx-badges">
        <div class="ebanx-group">
            <a href="https://itunes.apple.com/br/app/ebanx/id1062597149?mt=8" target="_blank">
                <img src="<?= $skin . 'frontend/base/default/ebanx/badge-apple.png' ?>" alt="">
            </a>
        </div>
        <div class="ebanx-group">
            <a href="https://play.google.com/store/apps/details?id=ebanx.ebanx&hl=en" target="_blank">
                <img src="<?= $skin . 'frontend/base/default/ebanx/badge-google.png' ?>" alt="">
            </a>
        </div>
    </div>

</div>
