<?php
$order = $this->getOrder();
?>
<div class="ebanx-details">
    <p><?= trim($order->getBillingAddress()->getFirstname()) ?>, su boleta Baloto fue generado con éxito.</p>
    <p>Una copia de la boleta fue enviada al correo electrónico <strong><?= $order->getBillingAddress()->getEmail() ?></strong>.</p>
    <p>Si tienes dudas, por favor escribe a <a href="mailto:soporte@ebanx.com">soporte@ebanx.com</a>.</p>

    <div class="ebanx-groups">
        <div class="ebanx-group">
            <a href="<?= $this->getEbanxUrlPdf() ?>" target="_blank"
               class="button banking-ticket__action"><?php echo $this->__('Salvar em PDF'); ?></a>
        </div>
        <div class="ebanx-group">
            <a href="<?= $this->getEbanxUrlPrint() ?>" target="_blank"
               class="button banking-ticket__action"><?php echo $this->__('Imprimir boleto'); ?></a>
        </div>
    </div>
    <div>
        <iframe id="ebanx-baloto-frame" src="<?php echo $this->getVoucherUrl(); ?>"
                style="width: 100%; border: 0px; height: 1000px"></iframe>
    </div>

    <?php include 'apps.phtml' ?>
</div>
