<?php
$order = $this->getOrder();
$payment = $this->getPayment();
?>
<div class="ebanx-details">
  <? if ($order->getStatus() === 'pending') { ?>
    <p>Obrigado! Seu pedido foi recebido e seu pagamento está em processo de análise.</p>
  <? } else { ?>
    <p><strong><?= trim($order->getBillingAddress()->getFirstname()) ?></strong>, seu pagamento de
        <strong><?= $this->formatPriceWithLocalCurrency($this->currencyCode, $payment->getEbanxLocalAmount()); ?></strong>
        foi aprovado o/</p>
    <p>Se tiver alguma dúvida em relação ao seu pagamento, acesse a Conta EBANX com o email
        <strong><?= $order->getBillingAddress()->getEmail() ?></strong>.</p>

  <? } ?>
  <?php include 'apps.phtml' ?>
</div>
