<?php
$order = $this->getOrder();
$payment = $this->getPayment();
?>
<div class="ebanx-details">
    <p>¡Listo <?= $order->getBillingAddress()->getFirstname() ?>!</p>
    <p>Acabamos de confirmar la operación y procesaremos tu orden. Imprime tu cupón y acércate a cualquier centro
        autorizado para realizar tu pago.</p>
    <p>Una copia del cupón fue enviada al correo electrónico: <strong><?= $order->getBillingAddress()->getEmail() ?></strong></p>
    <p>Si tienes dudas, por favor escribe a <a href="mailto:soporte@ebanx.com">soporte@ebanx.com</a>.</p>

    <div class="ebanx-groups">
        <a href="<?= $this->getEbanxUrlPrint() ?>" target="_blank" class="button">Imprimir Voucher</a>
    </div>

    <div class="ebanx-cash-payment">
        <iframe id="ebanx-pagoefectivo-frame" src="<?php echo $this->getVoucherUrl(); ?>"
                style="width: 100%; border: 0px; height: 1000px"></iframe>
    </div>

    <?php include 'apps.phtml' ?>
</div>
